# Site settings
title: Brett Blue
description: Brett Blue's Personal Website
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Brett Blue
user_description: I'm a senior technical writer who's passionate about creating clear and robust documentation that distills complex information into an easy-to-read format for users. I enjoy using my technical background and communication expertise to create useful documentation for developers. 
user_title: Technical Writer
email: brettb@hey.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
github_username: brettbblue
baseurl: ""
url: "https://brettblue.io"
